# Generated by Django 3.2.15 on 2022-08-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default='', max_length=100, unique=True, verbose_name='member_id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=1000, verbose_name='email')),
                ('points', models.IntegerField(verbose_name='points')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, verbose_name='store_id')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='payment_id')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='payment_method')),
                ('offering_method', models.CharField(blank=True, max_length=100, verbose_name='offering_method')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('product_id', models.CharField(blank=True, max_length=100, verbose_name='product_id')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='product_name')),
                ('price', models.IntegerField(blank=True, verbose_name='price')),
                ('tax', models.CharField(blank=True, max_length=100, verbose_name='tax')),
                ('price_including_tax', models.IntegerField(verbose_name='price_including_tax')),
                ('user_id', models.CharField(blank=True, max_length=100, verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, verbose_name='store_id')),
                ('payment_id', models.CharField(max_length=100, verbose_name='payment_id')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='payment_method')),
                ('offering_method', models.CharField(blank=True, max_length=100, verbose_name='offering_method')),
                ('time', models.CharField(max_length=100, verbose_name='time')),
                ('product_id', models.CharField(blank=True, max_length=100, verbose_name='product_id')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='product_name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('tax', models.CharField(blank=True, max_length=100, verbose_name='tax')),
                ('price_including_tax', models.IntegerField(verbose_name='price_including_tax')),
                ('member_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.member', verbose_name='member_id')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
