# Generated by Django 3.2.15 on 2022-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, verbose_name='store_id')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='payment_id')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='payment_method')),
                ('offering_method', models.CharField(blank=True, max_length=100, verbose_name='offering_method')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('product_id', models.CharField(blank=True, max_length=100, verbose_name='product_id')),
                ('product_name', models.CharField(blank=True, max_length=100, verbose_name='product_name')),
                ('price', models.IntegerField(blank=True, verbose_name='price')),
                ('tax', models.CharField(blank=True, max_length=100, verbose_name='tax')),
                ('price_including_tax', models.IntegerField(verbose_name='price_including_tax')),
                ('user_id', models.CharField(blank=True, max_length=100, verbose_name='user_id')),
            ],
        ),
    ]
