# Generated by Django 3.2.15 on 2022-08-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='member_id',
            field=models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.PROTECT, to='blog.member', verbose_name='member_id'),
        ),
    ]
