# Generated by Django 3.2.15 on 2022-08-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
