# Generated by Django 3.2.15 on 2022-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sell_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=1000, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='points'),
        ),
    ]
