# Generated by Django 3.2.15 on 2022-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='payment_id',
            field=models.CharField(max_length=100, verbose_name='payment_id'),
        ),
    ]
