# Generated by Django 3.2.15 on 2022-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_sell_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='quantity',
            field=models.IntegerField(default=-1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='time',
            field=models.CharField(max_length=100, verbose_name='time'),
        ),
    ]
