# Generated by Django 3.2.15 on 2022-08-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220814_1833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sell',
            table='sell',
        ),
    ]
