# Generated by Django 3.2.15 on 2022-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_sell_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sell',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='sell',
            table=None,
        ),
    ]
